jkuester/unlauncher

- .github/workflows/android_tag_ci.yml
Add workflow for creating a new GitHub release and building/uploading a copy of the app when a tag is pushed.
> Add android tag ci workflow

- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
Previously Unlauncher was using `Locale.ROOT` when formatting the date/time on the home screen.  This [caused issues](https://github.com/jkuester/unlauncher/issues/33) with the date display in Android 11.  
This PR updates the date/time display format to use the default locale settings for the device. This fixes the mentioned formatting issue and should better localize the app for global users.
Closes #33
> Update locale used for date/time to be the device default

- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
Bringing up the app drawer gives focus to the search field. This focus is never removed when we launch an app,
causing the keyboard to come up when we return to the main launcher view as described in #38.
Added a call to clearFocus() on the search field in onAppClicked(), removing the focus from the search field
and allowing us to return to the launcher without opening the keyboard as expected.
Closes #38
> Remove focus from search field on app launch

- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/AddAppFragment.kt
- app/src/main/res/values-zh-rCN/strings.xml
This fixes a few more cases where the keyboard is not being hidden in addition to #40:
* fix the keyboard staying open after swiping down from the app drawer
* fix the keyboard staying open after adding an app to the home screen
* fix all cases of the edit box staying in focus after opening another app in any way (by moving the `clearFocus` call to `onStop`)
> Fixing more keyboard issues

- app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/dialogs/ChooseQuickButtonDialog.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeQuickButtonsFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/OptionsFragment.kt
- app/src/main/res/drawable/ic_empty.xml
- app/src/main/res/layout/customize_quick_buttons_fragment.xml
- app/src/main/res/layout/imageview_border.xml
- app/src/main/res/layout/options_fragment.xml
- app/src/main/res/navigation/nav_graph.xml
- app/src/main/res/values/strings.xml
Adds support for accessing the Unlauncher settings by long-pressing anywhere on the home screen.
Also adds support for customizing the visibility of the quick-buttons (with the goal of eventually being able to fully customize these buttons with future updates).
Closes #36
> Support long-press for settings and hiding quick buttons

- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
This avoids setting the listener every time onResume is called
which made the search really slow after many searches.
> Moved home search listener from onResume to onActivityCreated

- app/build.gradle.kts
- app/src/main/java/com/sduduzog/slimlauncher/datasource/QuickButtonPreferencesRepository.kt
- app/src/main/java/com/sduduzog/slimlauncher/datasource/QuickButtonPreferencesSerializer.kt
- app/src/main/java/com/sduduzog/slimlauncher/datasource/UnlauncherDataSource.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/dialogs/ChooseQuickButtonDialog.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeQuickButtonsFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/utils/BaseFragment.kt
- app/src/main/proto/unlauncher_data.proto
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
The Proto DataStore has a few benefits over the existing code that was using SharedPreferences. You can store more complex strongly typed data than just a bunch of key-value pairs.  But at the same time, you do not have to deal with the extra overhead of a "real" database/ORM.  
My hope is to be able to expand the Unlauncher data model in the future using this as the pattern.
> Convert Unlauncher preferences to use the Proto DataStore instead of SharedPreferences

- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
I believe this is a proper and permanent fix for the performance issues mentioned in #72.  Basically, we want to check which apps are currently installed on the device when Unlauncher resumes since that is how the contents of the app drawer are kept up to date (I don't know of any kind of `LiveData` style stream that we could subscribe to for those changes....).  However, on some devices that check takes several seconds (probably depends on devices resources and the number of apps installed). 
This PR updates the code for checking the currently installed apps to do it in a background IO thread Instead of blocking the UI thread for the check. This lets the app load immediately while any changes to the installed apps will be reflected in the drawer as soon as the info finishes loading. …
> Load the installed apps in IO thread on resume

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
Resolving #30 and scratching my own itches.
I've never used MotionLayout before, so hope I used the _right_ properties here. They do the job though.
As for the status bar extension, that seems to be _the way_ to do this. I haven't found this documented in the Android docs and it's a recurring theme in all related SO questions (e.g. [here](https://stackoverflow.com/a/14320900)). As the min SDK version here is 21, I went for `expandNotificationsPanel` directly.
<details>
<summary>Demo gif</summary>
</details>
Closes #30
> Expand status bar on swipe down

- app/src/main/res/values-it/strings.xml
Hello,
I'm trying to add Italian localization and I translated the available strings.
It seems there are some strings that are marked as "untranslatable" in the source file.
The string `remove_all_apps_dialog_title` is an example of this. Should such cases be translated too?
Anyway, I tried compiling and running Unlauncher on my phone, the localization seems to work :)
Hope it helps!
> Add Italian localization

- app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
- app/src/main/java/com/sduduzog/slimlauncher/datasource/UnlauncherDataSource.kt
- app/src/main/java/com/sduduzog/slimlauncher/datasource/apps/UnlauncherAppsRepository.kt
- app/src/main/java/com/sduduzog/slimlauncher/datasource/coreprefs/CorePreferencesRepository.kt
- app/src/main/java/com/sduduzog/slimlauncher/datasource/coreprefs/CorePreferencesSerializer.kt
- app/src/main/java/com/sduduzog/slimlauncher/di/ActivityModule.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeAppDrawerAppListFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeAppDrawerFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeQuickButtonsFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/OptionsFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/utils/BaseFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/utils/WallpaperManager.kt
- app/src/main/proto/core_preferences.proto
- app/src/main/proto/unlauncher_apps.proto
- app/src/main/res/layout/customize_app_drawer_fragment.xml
- app/src/main/res/layout/options_fragment.xml
Adds a new CorePreferences data source (with associated repository) for managing generic preferences such as the setting the wallpaper or opening the keyboard in the drawer.
Also does some other minor refactoring:
- Adds support for loading the UnlauncherDataSource via Hilt DI
- Moves logic for setting the wallpaper out of the MainActivity into a new WallpaperManager class
> Refactor preferences into a new core_preferences proto file

- app/src/main/java/com/sduduzog/slimlauncher/datasource/UnlauncherDataSource.kt
- app/src/main/java/com/sduduzog/slimlauncher/datasource/quickbuttonprefs/QuickButtonPreferencesMigrations.kt
- app/src/main/java/com/sduduzog/slimlauncher/datasource/quickbuttonprefs/QuickButtonPreferencesRepository.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/dialogs/ChooseQuickButtonDialog.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/options/CustomizeQuickButtonsFragment.kt
The Quick Button preferences were storing the _Resource Id_ of the icon that should be shown.  Unfortunately, Android Resource Ids are not consistent between different versions of an app.  So, upgrading the app changes all the Resource Ids (and the stored preference values no longer mapped to actual resources).
I have updated the value stored for the preference to just be an arbitrary `Int` value that I have manually mapped to the various Icon resources.  This seems best because I can reuse the same proto data structure to store the preference, but it will also remain consistent between different versions of the app.
I have added a new migration for the Quick Button preferences that will set the default icon pref values for any of the quick buttons that is not currently associated with a …
> Fix quick button preferences to not break when app is updated

- app/src/main/java/com/sduduzog/slimlauncher/MainActivity.kt
- app/src/main/java/com/sduduzog/slimlauncher/utils/BaseFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/utils/SystemUiManager.kt
Closes #131
The colors of the Navigation bar at the bottom of the screen have always just been left to the default (dark) system color. This looks fine for the dark themes, but as noted in the issue, it does not look great for the light themes.
@hayribakici set a good initial starting point in [this PR](https://github.com/jkuester/unlauncher/pull/132), but unfortunately, upon testing I found that modifying the theme resources was not going to work the best across a wide range of Android versions (or at least I could not figure it out).
That PR launched me down the rabbit-hole of trying to understand the right way to do this. I ended up finding layers of different support for various system APIs and functionality all for customizing the look of the status bar at the top and the navigation …
> fix(#131): set proper system UI colors for status and nav bars

- app/src/main/java/com/sduduzog/slimlauncher/adapters/AppDrawerAdapter.kt
When sorting apps during queries in the drawer place the apps whose name starts with the query first.
> feat(search): Prioritize apps starting with query

- app/src/main/res/layout/customize_app_drawer_fragment_search_field_options.xml
- app/src/main/res/layout/options_fragment.xml
Adds correct `textColor` in `SwitchCompat` buttons.
> fix(options): use correct text color in options switches

- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
- app/src/main/java/com/sduduzog/slimlauncher/utils/Utils.kt
This PR fixes #190 
I chose to just hide the uninstall option, because default launchers on android do the same. However, changing to put a notification instead should be doable with these given changes.
> fix(#190): hide uninstall option if app is system app.

- app/src/main/res/xml/home_motion_scene.xml
Moves the clock completely off-screen.
Closes #217
> fix(#217): totally hide Analog Clock in drawer

- app/src/main/res/layout/home_fragment_content.xml
- app/src/main/res/xml/home_motion_scene_bottom.xml
Could not reproduce the problem and therefor not check whether the fix works as expected. It broadens clock's width to its parent's width.
Hopefully (hate to write it) that fixes the problem.
> fix(#207): digital clock got line wrapped

- app/src/main/java/com/sduduzog/slimlauncher/ui/main/BinaryClockView.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/main/ClockView.kt
- app/src/main/java/com/sduduzog/slimlauncher/ui/main/HomeFragment.kt
Obeys the users wish to display a 24h binary clock.
Fixes #225
> fix(#225): 24-hour binary clock

- app/src/main/res/layout/home_fragment_content.xml
- app/src/main/res/xml/home_motion_scene_bottom.xml
This reverts commit 11cf002f4e38bae28af4739c63f3f5c50f08c6fd.
@khwolf, unfortunately I had to revert https://github.com/jkuester/unlauncher/pull/227.  I noticed later that for some reason, if you have the Search Field Position set to `Bottom`, then the alignment for the clock gets broken:
> Revert "fix(#207): digital clock got line wrapped (#227)"

- .github/workflows/android_branch_ci.yml
- .github/workflows/android_master_ci.yml
- .github/workflows/android_pr_ci.yml
- .github/workflows/android_release_ci.yml
- app/build.gradle.kts
Also fixes CI by upgrading GitHub CI action versions.
So far, there is one known issue in Android 15: https://github.com/jkuester/unlauncher/issues/251
That issue will need to be addressed before these changes can be released, but I am going to merge this now to unblock other changes.
> Target Android 15
